baseURL = "https://kth-ml-seminars.netlify.app/"
languageCode = "en-us"
title = "KTH ML Seminars"
theme = "ink"
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
# disqusShortname = "ink-demo"

[params]
	# subtitle = "These focused seminars examine the specific details of various state-of-the-art papers in the CV/DL field. Please contact Hossein Azizpour (azizpour@kth.se) if you would like to deliver a seminar or to suggest a colleague."

	# Optional 64x64 avatar image.
	avatar = "https://pbs.twimg.com/profile_images/972081577256783874/2vzBcbrQ.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "All seminars"
url = "/"
weight = 1

# [[menu.main]]
# name = "All seminars"
# url = "/posts"
# weight = 2

# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 2

[[menu.main]]
name = "Upcoming seminars"
url = "/tags/upcoming-seminars"
weight = 2

[[menu.main]]
name = "Past seminars"
url = "/tags/past-seminars"
weight = 3

# [[params.social]]
# name = "Github"
# icon = "github"
# url = "https://github.com/knadh/hugo-ink"

# [[params.social]]
# name = "RSS"
# icon = "rss"
# url = "/index.xml"

[taxonomies]
   tag = "tags"
